version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./:/app
      - ./tenders.csv:/app/tenders.csv
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./tenders.csv:/app/tenders.csv
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis
      - worker
